source 'https://rubygems.org'

gem 'rails', '4.0.0'

group :development, :test do
  gem 'sqlite3', '1.3.8'
  gem 'rspec-rails', '2.11.0'
  gem 'annotate', '2.5.0'
end

group :assets do
  gem 'sass-rails',   '~> 4.0.0'
  gem 'coffee-rails', '~> 4.0.0'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', platforms: :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

gem 'turbolinks'

gem 'jbuilder', '~> 1.0.1'



group :test do
  gem 'capybara', '1.1.2'
end

gem 'bootstrap-sass'